feat: 🎸 image endpoint
ImageingApp/Website pull request #2
Opened 2022-07-20 20:04 UTC by thehairy

2022-07-20 20:52 UTC, thehairy commented on pages/api/image.ts
> +        const form = new IncomingForm({
Have to think about a different way on handling those images.
I cant save them to the server with Netlify/Vercel.

2022-07-21 11:48 UTC, twisttaan requested changes
LGTM, just address requests.

2022-07-21 11:48 UTC, twisttaan commented on pages/api/image.ts
> +                            error: 'You are not authorized for this endpoint. Please provide a valid token or get support at \'https://imageing.org/discord\'.',
You should make some error class to pass a code (enum) and message.

2022-07-21 11:48 UTC, twisttaan commented on pages/api/image.ts
> +                    return res.status(500).json({ error: 'There has been an issue on server side. Please try again or get support at \'https://imageing.org/discord\'.' });
You should make some error class to pass a code (enum) and message.

2022-07-21 11:48 UTC, twisttaan commented on pages/api/image.ts
> +                return res.status(40).json({ error: 'Provide a file to the request body. Please try again or get support at \'https://imageing.org/discord\'.' });
You should make some error class to pass a code (enum) and message.

2022-07-22 15:08 UTC, thehairy commented
Will move the api to a different repo and host it myself.

2022-07-22 15:08 UTC, closed without merging